apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: configuration-aws-identity-center-v1alpha1-1
spec:
  compositeTypeRef:
    apiVersion: aws.hops.ops.com.ai/v1alpha1
    kind: IdentityCenter
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-configuration-aws-identity-centerrender
    step: render
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
