apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: identitycenters.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: IdentityCenter
    plural: identitycenters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        description: IdentityCenter provisions AWS Identity Center instances, local users, permission sets, and account assignments.
        required:
        - spec
        properties:
          spec:
            type: object
            description: Desired Identity Center configuration.
            required:
            - managementPolicies
            properties:
              organizationName:
                type: string
                description: Logical name used for tagging and naming rendered resources. Defaults to metadata.name.
              region:
                type: string
                description: AWS region for Identity Center and Identity Store resources.
              managementMode:
                type: string
                description: Controls whether Hops or the caller manages downstream consumers. Defaults to self.
                enum:
                - self
                - managed
                default: self
              deletionPolicy:
                type: string
                description: Delete or Orphan composed resources when the XR is removed.
                default: Delete
              managementPolicies:
                type: array
                description: Management operations allowed on composed resources. Use ["*"] for full management or omit Delete to orphan.
                items:
                  type: string
                  enum:
                  - "*"
                  - Create
                  - Observe
                  - Update
                  - Delete
                  - LateInitialize
                default:
                - "*"
              providerConfigName:
                type: string
                description: ProviderConfig used for all AWS API calls. Defaults to metadata.name.
              identityCenter:
                type: object
                description: Optional overrides for the Identity Center instance.
                properties:
                  instanceArn:
                    type: string
                    description: Identity Center instance ARN (arn:aws:sso:::instance/ssoins-1234567890abcdef). If not provided, the composition will create a new instance.
                  relayState:
                    type: string
                    description: Default relay state for permission sets.
                  sessionDuration:
                    type: string
                    description: Default session duration (ISO8601). Defaults to PT1H.
                  tags:
                    type: object
                    description: Extra tags merged onto permission sets.
                    x-kubernetes-preserve-unknown-fields: true
              identityStore:
                type: object
                description: Identity Store configuration when rendering local users and groups.
                properties:
                  id:
                    type: string
                    description: Identity Store ID (for example, d-1234567890). If not provided, will be derived from the Identity Center instance.
              groups:
                type: array
                description: Optional list of Identity Store groups to create.
                items:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                      description: Logical group name.
                    displayName:
                      type: string
                    description:
                      type: string
                    tags:
                      type: object
                      description: Extra labels mirrored onto the metadata.labels map.
                      x-kubernetes-preserve-unknown-fields: true
              users:
                type: array
                description: Optional list of users to create in the Identity Store.
                items:
                  type: object
                  required:
                  - email
                  - username
                  properties:
                    username:
                      type: string
                      description: Identity Store username.
                    email:
                      type: string
                    firstName:
                      type: string
                    lastName:
                      type: string
                    displayName:
                      type: string
                    groups:
                      type: array
                      description: Group names the user should join.
                      items:
                        type: string
                    tags:
                      type: object
                      description: Extra labels mirrored onto the metadata.labels map.
                      x-kubernetes-preserve-unknown-fields: true
              permissionSets:
                type: array
                description: Optional permission sets plus account assignments.
                items:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                      description: Name of the permission set presented in the AWS console.
                    description:
                      type: string
                    relayState:
                      type: string
                    sessionDuration:
                      type: string
                    inlinePolicy:
                      type: string
                      description: Inline JSON policy document attached to the permission set.
                    managedPolicies:
                      type: array
                      description: AWS managed policy ARNs to attach.
                      items:
                        type: string
                    customerManagedPolicies:
                      type: array
                      description: Customer managed policy references to attach.
                      items:
                        type: object
                        required:
                        - name
                        properties:
                          name:
                            type: string
                            description: Name of the IAM policy.
                          path:
                            type: string
                            description: Path containing the IAM policy. Defaults to /.
                    tags:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    assignToAccounts:
                      type: array
                      description: AWS account identifiers that should receive assignments.
                      items:
                        type: string
                    assignToGroups:
                      type: array
                      description: Identity Store group names that should receive assignments.
                      items:
                        type: string
                    assignToUsers:
                      type: array
                      description: Local user names that should receive assignments.
                      items:
                        type: string
                    assignments:
                      type: array
                      description: Advanced account assignments applied to this permission set.
                      items:
                        type: object
                        required:
                        - accountId
                        properties:
                          accountId:
                            type: string
                          principal:
                            type: object
                            description: Preferred way to reference principals.
                            properties:
                              type:
                                type: string
                                enum:
                                - USER
                                - GROUP
                              id:
                                type: string
                              name:
                                type: string
                          principalType:
                            type: string
                            description: Deprecated; prefer principal.type.
                          principalId:
                            type: string
                            description: Deprecated; prefer principal.id.
              externalIdP:
                type: object
                description: Optional external identity provider integration.
                properties:
                  type:
                    type: string
                    enum:
                    - oidc
                    - saml
                  issuerUrl:
                    type: string
                  clientIdSecretRef:
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      key:
                        type: string
                  clientSecretSecretRef:
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      key:
                        type: string
          status:
            type: object
            description: Observed state for IdentityCenter.
            properties:
              organizationName:
                type: string
              managementMode:
                type: string
              identityCenter:
                type: object
                properties:
                  instanceArn:
                    type: string
                  ready:
                    type: boolean
              identityStore:
                type: object
                properties:
                  id:
                    type: string
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        id:
                          type: string
                          nullable: true
                  groups:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        id:
                          type: string
                          nullable: true
              permissionSets:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    arn:
                      type: string
                      nullable: true
                    assignments:
                      type: array
                      items:
                        type: object
                        properties:
                          accountId:
                            type: string
                          principalType:
                            type: string
                          principalId:
                            type: string
                            nullable: true
                          principalName:
                            type: string
        
