apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: IdentityCenter
metadata:
  name: platform-sso
  namespace: default
spec:
  managementPolicies: ["*"]
  providerConfigName: aws-provider
  region: us-east-1
  identityCenter:
    instanceArn: arn:aws:sso:::instance/ssoins-1234567890abcdef
    sessionDuration: PT2H
  identityStore:
    id: d-1234567890
  groups:
    - name: Admins
      displayName: Platform Admins
  users:
    - username: platform-admin
      email: platform-admin@example.com
      firstName: Platform
      lastName: Admin
      groups: [Admins]
  permissionSets:
    - name: AdminAccess
      description: Full admin access
      managedPolicies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      assignToGroups: [Admins]
      assignToAccounts: ["123456789012"]
