apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: IdentityCenter
metadata:
  name: workloads-sso
  namespace: default
spec:
  organizationName: workloads
  managementPolicies: ["*"]
  providerConfigRef:
    name: aws-provider
  region: us-east-1
  identityStoreId: d-0987654321
  identityCenter:
    instanceArn: arn:aws:sso:::instance/ssoins-abcdef0123456789
    relayState: https://console.aws.amazon.com/
  groups:
    - name: WorkloadsEngineering
      displayName: Workloads Engineering
  users:
    - username: workloads-reader
      email: reader@example.com
      displayName: Workloads Reader
      groups: [WorkloadsEngineering]
  permissionSets:
    - name: workloads-readonly
      assignToGroups: [WorkloadsEngineering]
      assignToAccounts: ["210987654321"]
      inlinePolicy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ec2:Describe*"
              ],
              "Resource": "*"
            }
          ]
        }
      customerManagedPolicies:
        - name: CustomAudit
          path: /auditors/
      assignments:
        - accountId: "999999999999"
          principal:
            type: USER
            name: workloads-reader
